### ISSUE TITLE
Vagrant -paketin kanssa ongelmia MAC:issa

### ISSUE THREAD

**Issue by apoikola** [yhteentoimivuuspalvelut/ytp#3]
Tällainen virhe ilmoitus tuli, kun ajoi vagrant upin:

<pre>
TASK: [common_webserver | Package modules] ************************************ 
failed: [10.10.10.10 -> 127.0.0.1] => (item=ytp-assets-common) => {"changed": true, "cmd": ["tar", "cf", "ytp-assets-common.tar", "ytp-assets-common", "--exclude=.git", "--exclude-from=ytp-assets-common/.gitignore"], "delta": "0:00:00.021342", "end": "2014-09-26 19:02:43.292957", "item": "ytp-assets-common", "rc": 1, "start": "2014-09-26 19:02:43.271615"}
stderr: tar: --exclude=.git: Cannot stat: No such file or directory
tar: --exclude-from=ytp-assets-common/.gitignore: Cannot stat: No such file or directory
tar: Error exit delayed from previous errors.
failed: [10.10.10.10 -> 127.0.0.1] => (item=ckanext-drupal7) => {"changed": true, "cmd": ["tar", "cf", "ckanext-drupal7.tar", "ckanext-drupal7", "--exclude=.git", "--exclude-from=ckanext-drupal7/.gitignore"], "delta": "0:00:00.005832", "end": "2014-09-26 19:02:43.386283", "item": "ckanext-drupal7", "rc": 1, "start": "2014-09-26 19:02:43.380451"}
stderr: tar: --exclude=.git: Cannot stat: No such file or directory
tar: --exclude-from=ckanext-drupal7/.gitignore: Cannot stat: No such file or directory
tar: Error exit delayed from previous errors.
failed: [10.10.10.10 -> 127.0.0.1] => (item=ckanext-ytp-drupal) => {"changed": true, "cmd": ["tar", "cf", "ckanext-ytp-drupal.tar", "ckanext-ytp-drupal", "--exclude=.git", "--exclude-from=ckanext-ytp-drupal/.gitignore"], "delta": "0:00:00.007774", "end": "2014-09-26 19:02:43.479756", "item": "ckanext-ytp-drupal", "rc": 1, "start": "2014-09-26 19:02:43.471982"}
stderr: tar: --exclude=.git: Cannot stat: No such file or directory
tar: --exclude-from=ckanext-ytp-drupal/.gitignore: Cannot stat: No such file or directory
tar: Error exit delayed from previous errors.
failed: [10.10.10.10 -> 127.0.0.1] => (item=ckanext-ytp-tasks) => {"changed": true, "cmd": ["tar", "cf", "ckanext-ytp-tasks.tar", "ckanext-ytp-tasks", "--exclude=.git", "--exclude-from=ckanext-ytp-tasks/.gitignore"], "delta": "0:00:00.006098", "end": "2014-09-26 19:02:43.570538", "item": "ckanext-ytp-tasks", "rc": 1, "start": "2014-09-26 19:02:43.564440"}
stderr: tar: --exclude=.git: Cannot stat: No such file or directory
tar: --exclude-from=ckanext-ytp-tasks/.gitignore: Cannot stat: No such file or directory
tar: Error exit delayed from previous errors.
failed: [10.10.10.10 -> 127.0.0.1] => (item=ckanext-ytp-request) => {"changed": true, "cmd": ["tar", "cf", "ckanext-ytp-request.tar", "ckanext-ytp-request", "--exclude=.git", "--exclude-from=ckanext-ytp-request/.gitignore"], "delta": "0:00:00.006261", "end": "2014-09-26 19:02:43.661039", "item": "ckanext-ytp-request", "rc": 1, "start": "2014-09-26 19:02:43.654778"}
stderr: tar: --exclude=.git: Cannot stat: No such file or directory
tar: --exclude-from=ckanext-ytp-request/.gitignore: Cannot stat: No such file or directory
tar: Error exit delayed from previous errors.
failed: [10.10.10.10 -> 127.0.0.1] => (item=ckanext-ytp-main) => {"changed": true, "cmd": ["tar", "cf", "ckanext-ytp-main.tar", "ckanext-ytp-main", "--exclude=.git", "--exclude-from=ckanext-ytp-main/.gitignore"], "delta": "0:00:00.012360", "end": "2014-09-26 19:02:43.758000", "item": "ckanext-ytp-main", "rc": 1, "start": "2014-09-26 19:02:43.745640"}
stderr: tar: --exclude=.git: Cannot stat: No such file or directory
tar: --exclude-from=ckanext-ytp-main/.gitignore: Cannot stat: No such file or directory
tar: Error exit delayed from previous errors.
failed: [10.10.10.10 -> 127.0.0.1] => (item=ckanext-googleanalytics) => {"changed": true, "cmd": ["tar", "cf", "ckanext-googleanalytics.tar", "ckanext-googleanalytics", "--exclude=.git", "--exclude-from=ckanext-googleanalytics/.gitignore"], "delta": "0:00:00.006342", "end": "2014-09-26 19:02:43.857926", "item": "ckanext-googleanalytics", "rc": 1, "start": "2014-09-26 19:02:43.851584"}
stderr: tar: --exclude=.git: Cannot stat: No such file or directory
tar: --exclude-from=ckanext-googleanalytics/.gitignore: Cannot stat: No such file or directory
tar: Error exit delayed from previous errors.
failed: [10.10.10.10 -> 127.0.0.1] => (item=ytp-theme-drupal) => {"changed": true, "cmd": ["tar", "cf", "ytp-theme-drupal.tar", "ytp-theme-drupal", "--exclude=.git", "--exclude-from=ytp-theme-drupal/.gitignore"], "delta": "0:00:00.008279", "end": "2014-09-26 19:02:43.951074", "item": "ytp-theme-drupal", "rc": 1, "start": "2014-09-26 19:02:43.942795"}
stderr: tar: --exclude=.git: Cannot stat: No such file or directory
tar: --exclude-from=ytp-theme-drupal/.gitignore: Cannot stat: No such file or directory
tar: Error exit delayed from previous errors.
failed: [10.10.10.10 -> 127.0.0.1] => (item=ytp-drupal-wysiwyg) => {"changed": true, "cmd": ["tar", "cf", "ytp-drupal-wysiwyg.tar", "ytp-drupal-wysiwyg", "--exclude=.git", "--exclude-from=ytp-drupal-wysiwyg/.gitignore"], "delta": "0:00:00.005302", "end": "2014-09-26 19:02:44.037358", "item": "ytp-drupal-wysiwyg", "rc": 1, "start": "2014-09-26 19:02:44.032056"}
stderr: tar: --exclude=.git: Cannot stat: No such file or directory
tar: --exclude-from=ytp-drupal-wysiwyg/.gitignore: Cannot stat: No such file or directory
tar: Error exit delayed from previous errors.
failed: [10.10.10.10 -> 127.0.0.1] => (item=ytp-drupal-user) => {"changed": true, "cmd": ["tar", "cf", "ytp-drupal-user.tar", "ytp-drupal-user", "--exclude=.git", "--exclude-from=ytp-drupal-user/.gitignore"], "delta": "0:00:00.005638", "end": "2014-09-26 19:02:44.132079", "item": "ytp-drupal-user", "rc": 1, "start": "2014-09-26 19:02:44.126441"}
stderr: tar: --exclude=.git: Cannot stat: No such file or directory
tar: --exclude-from=ytp-drupal-user/.gitignore: Cannot stat: No such file or directory
tar: Error exit delayed from previous errors.

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/Users/apoikola/single-server.retry

10.10.10.10                : ok=35   changed=5    unreachable=0    failed=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
</pre>

**Comment by Vilsepi** [comment]
Closed due to inactivity. Please reopen if the issue persists.
