### ISSUE TITLE
Increase publishable dataset size

### ISSUE THREAD

**Issue by haphut** [yhteentoimivuuspalvelut/ytp#4]
The current size limit for datasets, 50 MB, seems too small. It's unnecessarily hard to publish when the data needs to be split into pieces first. Similarly the user needs to glue the pieces back together. Is there a specific reason for the low limit? Thanks for your work.

**Comment by Vilsepi** [comment]
The limit is arbitrary. It was chosen due to a decision that avoindata.fi is not primarily a file hosting service. Organizations that might have a bunch of pdf files or small excel sheets can easily share them without a hosting of their own, but organizations that have a massive amount of data should host the data by themselves and provide an API.

We will discuss this internally whether the limit could be raised.

**Comment by haphut** [comment]
Thanks for the quick reply.

I'm surprised. I thought the very purpose of [avoindata.fi](https://www.avoindata.fi) is to offer centralized publishing for organizations that have not yet established their own machinery for opening data. That would be the vast majority of Finnish public sector organizations.

I'm sure people have diverse opinions on what is a massive amount of data in this context. Yet would you not agree that 50 MB is a very conservative limit for non-massive data? FYI, here's [an example of a dataset](https://www.avoindata.fi/data/fi/dataset/rakennusten-aanestysalueet) that was split because of the size limit.

Do I understand correctly that your service is primarily meant for publishing PDF files and Excel sheets? In my view those formats do not fit the definition of open data which requires a ["machine-readable" and "convenient and modifiable form"](http://opendefinition.org/od/#open-format).

**Comment by Zharktas** [comment]
It has been requested before, but there are issues that need to be solved before we can offer proper hosting for open data. For example current hosting solution for avoindata.fi, does not scale to accommodate larger amount of data. So the current solution is to host the data in any webserver and link it to avoindata.fi even though it is not optimal.

If it is decided to provide hosting, it will be announced at least in the front page of avoindata.fi and social media.

**Comment by haphut** [comment]
Thanks. I hope hosting finds its way onto your roadmap.
Okay, I found where you [discourage PDFs and Excel files](https://www.avoindata.fi/fi/content/julkaise-aineistoja). Nice to see that you do.

**Comment by Zharktas** [comment]
Resource size has been increased to 150MB, it won't be enough for larger datasets but it solves some issues with resources.
